### PR TITLE
driver/overlay: fix concurrent map write on stagingDirsLocks

### LINKED ISSUE #2297: concurrent map writes in overlay driver
```
<+063ms> # # podman run -d --name myweb -p 5123:80 -v /tmp/CI_s2PP/podman_bats.MFc4Ej/myimage-t8GqI3Z5.tar:/var/www/image.tar:Z -w /var/www quay.io/libpod/testimage:20241011 /bin/busybox-extras httpd -f -p 80
<+084ms> # Trying to pull quay.io/libpod/testimage:20241011...
         # Getting image source signatures
         # Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
         # Copying blob sha256:33b517cffde0ecb1f424f107b005cdfd614c467b9de2ad334970f800b77a4e70
         # fatal error: concurrent map writes
         #
         # goroutine 66 [running]:
         # internal/runtime/maps.fatal({0x1e0a955?, 0x43?})
         # 	/usr/lib/golang/src/runtime/panic.go:1058 +0x18
         # github.com/containers/storage/drivers/overlay.(*Driver).ApplyDiffWithDiffer(0xc000145d40, 0xc000103340?, {0x214cfc0, 0xc000468000?})
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/storage/drivers/overlay/overlay.go:2242](https://github.com/containers/storage/blob/45e051377c44037fbedecf66ae940ad28d16b557/drivers/overlay/overlay.go#L2242) +0x465
         # github.com/containers/storage.(*layerStore).applyDiffWithDifferNoLock(0xc00040c9c0?, 0x0, {0x214cfc0, 0xc000468000})
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/storage/layers.go:2567](https://github.com/containers/storage/blob/45e051377c44037fbedecf66ae940ad28d16b557/layers.go#L2567) +0xe4
         # github.com/containers/storage.(*store).PrepareStagedLayer(0x214bd20?, 0x0, {0x214cfc0, 0xc000468000})
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/storage/store.go:3117](https://github.com/containers/storage/blob/45e051377c44037fbedecf66ae940ad28d16b557/store.go#L3117) +0x53
         # github.com/containers/image/v5/storage.(*storageImageDestination).PutBlobPartial(0xc000503c00, {0x215ac40, 0x3015380}, {0x214bc00, 0xc000012468}, {{0xc00004e6e0, 0x47}, 0x556018, {0x0, 0x0, ...}, ...}, ...)
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/image/v5/storage/storage_dest.go:417](https://github.com/containers/image/blob/45e051377c44037fbedecf66ae940ad28d16b557/v5/storage/storage_dest.go#L417) +0x332
         # github.com/containers/image/v5/copy.(*imageCopier).copyLayer.func2(0xc0001d9b00, 0x0?, {{0xc00004e6e0, 0x47}, 0x556018, {0x0, 0x0, 0x0}, 0x0, {0xc0002b4150, ...}, ...}, ...)
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/image/v5/copy/single.go:815](https://github.com/containers/image/blob/45e051377c44037fbedecf66ae940ad28d16b557/v5/copy/single.go#L815) +0x258
         # github.com/containers/image/v5/copy.(*imageCopier).copyLayer(0xc0001d9b00, {0x215ac40, 0x3015380}, {{0xc00004e6e0, 0x47}, 0x556018, {0x0, 0x0, 0x0}, 0x0, ...}, ...)
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/image/v5/copy/single.go:837](https://github.com/containers/image/blob/45e051377c44037fbedecf66ae940ad28d16b557/v5/copy/single.go#L837) +0x9f6
         # github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func1(0x0, {{0xc00004e6e0, 0x47}, 0x556018, {0x0, 0x0, 0x0}, 0x0, {0xc0002b4150, 0x2b}, ...}, ...)
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/image/v5/copy/single.go:486](https://github.com/containers/image/blob/45e051377c44037fbedecf66ae940ad28d16b557/v5/copy/single.go#L486) +0x392
         # created by github.com/containers/image/v5/copy.(*imageCopier).copyLayers.func2 in goroutine 1
         # 	/var/tmp/go/src/github.com/containers/podman/vendor/github.com[/containers/image/v5/copy/single.go:526](https://github.com/containers/image/blob/45e051377c44037fbedecf66ae940ad28d16b557/v5/copy/single.go#L526) +0x14a
         #
```

seen in podman CI https://api.cirrus-ci.com/v1/artifact/task/5618317093765120/html/sys-podman-rawhide-root-host-sqlite.log.html
(v5.4 branch)

AFAICT nothing protects `stagingDirsLocks` map, it should have mutex I guess.

### PR DESCRIPTION
**Pull request by Luap99**
Seen in podman CI, a map by default in not concurrent safe. As the
driver can be used in parallel by callers we must guard against this
here.

Fixes #2297

--- 

drivers/overlay: use clear() for stagingDirsLocks

That should be more memory efficient as we do not have to allocate a new map.

### CODE REVIEW

**Review by cgwalters — APPROVED** [review]
Looks sane to me.

**Review by giuseppe — APPROVED** [review]
/lgtm

File: drivers/overlay/overlay.go [hunk 1]
```diff
@@ -130,6 +130,9 @@ type Driver struct {
 	usingMetacopy    bool
 	usingComposefs   bool
 
+	stagingDirsLocksMutex *sync.Mutex
```
Comment (mtrmac) [inline drivers/overlay/overlay.go:133]: For future reference, I think it’s a bit more idiomatic not to use pointers for `Mutex` fields — that way linters can warn about unexpectedly making copies of the containing struct.

**Review by mtrmac — COMMENTED** [review]
LGTM, for the record.

File: drivers/overlay/overlay.go (hunk 1 above)
Comment (Luap99) [reply drivers/overlay/overlay.go:133]: > Actually, the supposedly-recommended/idiomatic way to express “don’t copy this type” is to add a mutex (-like method). Compare 

LOL, I keep the rewrite in rust comments to myself.
